### ISSUE TITLE
Datasets not showing on google

### ISSUE THREAD

**Issue by chaudj** [IQSS/dataverse.harvard.edu#1]
Data sets are not showing up on google search results. We are lucky they are being picked up by an external harvester that links to Dataverse otherwise, it would be impossible to find the data sets solely relying to google search. 

WorldFish Dataverse https://dataverse.harvard.edu/dataverse/worldfish

**Comment by landreev** [comment]
@chaudj Hello, I am now seeing your most recent datasets appear in Google search results; for example: 
![Screen Shot 2019-03-11 at 11 12 16 AM](https://user-images.githubusercontent.com/737558/54137248-acfebb80-43f3-11e9-8a1f-5030157ce4cb.png)
![Screen Shot 2019-03-11 at 11 12 57 AM](https://user-images.githubusercontent.com/737558/54137271-b556f680-43f3-11e9-916f-eefa2e36c0af.png)
![Screen Shot 2019-03-11 at 7 58 26 PM](https://user-images.githubusercontent.com/737558/54211262-66729500-44b7-11e9-8a6e-ddba219cb68b.png)
etc.
I haven't checked them all; but If any other datasets are still not showing as expected, hopefully the index will refresh shortly - because Google's crawler has accessed and read all of them in recent days.

**Comment by chaudj** [comment]
> @chaudj Hello, I am now seeing your most recent datasets appear in Google search results; for example:
> ![Screen Shot 2019-03-11 at 11 12 16 AM](https://user-images.githubusercontent.com/737558/54137248-acfebb80-43f3-11e9-8a1f-5030157ce4cb.png)
> ![Screen Shot 2019-03-11 at 11 12 57 AM](https://user-images.githubusercontent.com/737558/54137271-b556f680-43f3-11e9-916f-eefa2e36c0af.png)
> ![Screen Shot 2019-03-11 at 7 58 26 PM](https://user-images.githubusercontent.com/737558/54211262-66729500-44b7-11e9-8a6e-ddba219cb68b.png)
> etc.
> I haven't checked them all; but If any other datasets are still not showing as expected, hopefully the index will refresh shortly - because Google's crawler has accessed and read all of them in recent days.

Great! Thanks, Seems to be working okay since Monday!
