### ISSUE TITLE
Learn how users interpret proposed UI improvements in publishing workflow

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse.harvard.edu#109]
This issue is to define and track a research effort to learn more about delays in publishing datasets, and what users think of proposed efforts to make the need to publish more clear. 

Goals for testing:
- test the green success message with "publish" reminder text. Do people see it? Do they understand it? Does it influence them?
- test the more prominent "publish" button as in #7678. Do users see it? Does it influence them?
- determine why datasets that have been created may have gone unpublished.

The expected timeframe is to complete by the end of May. To do:
- [x]  identify datasets in Harvard and UNC with the following characteristics:
Depositors whose delayed publications *may* have been caused by an issue with the UI.

- Group by Dataverse collection to help with removing datasets where we know that the publishing delay has nothing to do with the UI, for example, the Harvard curation team knows that the publishing delay was because of some sort of embargo. Would be easy to also remove datasets that contain any language about an embargo.

For Harvard at least, the list would also contain:

- Depositors of datasets or dataset versions that have remained unpublished for a long time ("a long time" would be longer than the average age of unpublished datasets or dataset versions). In fact I've already made this list for the Harvard curation team. Can see if Odum is interested. Julian is contacting Don Sizemore about awareness of any publishing delays that might be related to the UI, and even provide database queries that they could run to find unpublished datasets/dataset versions.

- [x] create prototype pages to test 1) new messaging (#[7746](https://github.com/IQSS/dataverse/issues/7746)) 2) more prominent Publish button placement (#[7678](https://github.com/IQSS/dataverse/issues/7678))
- [x] define script for user sessions
- [x] contact and schedule user sessions

**Comment by jggautier** [comment]
It was easy to find a good-sized pool of depositors who:
- **Created just one dataset**: The more datasets they've created, I think the more likely it is that they learn to adapt to the software and realize that they need to publish
- **Created the dataset in the Root Dataverse collection**: Datasets deposited in user-created Dataverse collections are curated better in general, so it's more likely that someone else will notice that a dataset should have been published but hasn't been.
- **Created it 1-2 years ago**: The longer it's been since they created the dataset, the less likely they'll remember if there were UI issues and the more difficult it might be to contact them, but we don't want to contact depositors who created a dataset too recently
- **Haven't published the dataset**: It's simpler to find these unpublished datasets than it is to find published datasets with versions that have been unpublished for a certain length of time. I'm still doing this, but finding depositors of unpublished datasets was quicker and is arguably the more severe case (versus published datasets with a version that should have been published)

So I'm wondering if next we can review this pool of depositors' datasets.

And in the meantime I can chat with Don at Odum to see if they think that this might be a problem their depositors see and share some database queries they might use.

**Comment by jggautier** [comment]
There are 168 depositors of 166 datasets meeting the criteria I wrote about in this GitHub issue earlier.

To further remove datasets that might have been left unpublished for reasons unrelated to publication workflow confusion, I reviewed dataset metadata to remove test datasets and datasets with any indication of an intentional publication delay (like a statement about an embargo). Also cross-referenced the dataset contact email metadata with the emails used to contact the Dataverse support team (in the RT support system) to review previous communication with these depositors.

I think the 168 remaining depositors are a good pool to contact.

**Comment by TaniaSchlatter** [comment]
[Results from the small test](https://docs.google.com/document/d/14gUXOluY0F364QsXLP_bVnhoqRr3iQLRiqXCQ5F9qkI/edit).

Take-aways are:
- When there is no banner or button, all of the participants were all unable to identify how to move the dataset from draft to published. 
- None of the participants noticed the green banner consciously.
- Two out of three of the participants stated that they believe their dataset is published, when they are not. 
- One of the most helpful ways to get users to publish their dataset is to apply the prominent publish button which highlights to the user that they need to publish the dataset.  
- Regardless of the banner or new button, participants were confused when the dataset was actually published. One user asked if there would be an email confirmation that would be sent once the dataset was published. 

Another suggestion to help solve this confusion is to create a distinct notification at the top of the page once the dataset is published notifying the user that dataset is published. Two of the users asked “did it work?” once publishing the datasets because they were unclear if their dataset was published.

**Comment by TaniaSchlatter** [comment]
Issue [#7653](https://github.com/IQSS/dataverse/issues/7653) is related, as users mentioned not seeing a success message after publishing.
