### ISSUE TITLE
File PID registration turned off, but 27 files published in February have DOIs

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#11]
It looks like file PID registration was turned off in Harvard Dataverse in early January 2019 or earlier (judging from [a GitHub issue comment](https://github.com/IQSS/dataverse/issues/5427#issuecomment-451281561) Leonid made back then). Since then, 27 files were published with their own valid DOIs. All 27 are in [this dataset](https://doi.org/10.7910/DVN/E3WDFQ), published in its first dataset version on Feb 5. (A 28th file was added in the second dataset version, published on March 11, but that file does not have its own PID.)

Does anyone know why these 27 files have DOIs when the installation is configured to not register file PIDs?

**Comment by djbrooke** [comment]
@jggautier Good catch. I think I know what happened here. There was an accidental publish for this dataset by IFPRI in mid-November and they requested an unpublish almost immediately. Since there were no downloads and it was not cited anywhere, we unpublished. The file PIDs were probably generated then. I think it's OK to close, but we can talk more tomorrow.

**Comment by jggautier** [comment]
Thanks, Danny. That makes sense. Closing this issue.
