### ISSUE TITLE
Harvard Dataverse Repository Homepage Updates

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse.harvard.edu#115]
Two issues on the dataverse.harvard.edu homepage need to be addressed/revisited:

- We should un-comment-out the Recent Metrics that we removed during the production issues. This is the easy part!
- We should get the subjects metrics working again. See below for more info, copied from #114:

> The homepage queries for Dataset subject don't appear to be working
> 
> I was trying to use developer tools to edit this to point it to demo.dataverse.org (to see if this is a dataverse.harvard.edu issue) but my efforts were not successful. Here's what devtools flagged:

<img width="1317" alt="Screen Shot 2021-06-22 at 6 10 56 PM" src="https://user-images.githubusercontent.com/7773392/123136455-f175c000-d420-11eb-9b90-2159bf82a74d.png">

**Comment by pdurbin** [comment]
My guess is that the "bySubject" part (at least) of the example dynamic custom homepage in the docs is broken too: https://github.com/IQSS/dataverse/blob/v5.5/doc/sphinx-guides/source/_static/installation/files/var/www/dataverse/branding/custom-homepage-dynamic.html#L310

**Comment by landreev** [comment]
Per a quick slack investigation (thanks @pdurbin), it appears that the missing subjects are on account of a 5.5 change in the metrics API; specifically, the default output is now cvs, and json needs to be explicitly requested with an Accept: header. 
In java or python, the fix is a 1 line; something like `req.add_header(‘Accept’, ‘application/json’)`
There may not be a similarly trivial fix for javascript though. Not an expert by any means (so, correct me if I'm wrong), but from what I understand, the only way to add a header there is to switch to using XHR; with something along the lines of
```
const xhr = new XMLHttpRequest();

xhr.open('GET', metricBaseUrl + "dataverses/bySubject", true);
xhr.setRequestHeader('Accept', 'application/json');
xhr.send(null);
```
and then the output needs to be explicitly parsed, and the foreach loops in the current code, like this one: 
```
$.get(metricBaseUrl + "dataverses/bySubject", function(jData) {
   jData.data.forEach(function(item) {
   ...
   }   
```
rewritten accordingly.
Should still be simple of course.

**Comment by landreev** [comment]
(unless there's a way to ask for json with a query arg there - then it would be trivial...)

**Comment by djbrooke** [comment]
- @qqmyers will leave a note here with a possible path forward
- revisit the release notes (make sure we spell this out explicitly)

**Comment by qqmyers** [comment]
https://api.jquery.com/jquery.getjson/ and using $.getJSON instead of $.get . If not, the $.get and $.ajax calls can take an accepts param along with the ones for $.get.

**Comment by landreev** [comment]
Awesome, good to know. As I said, my knowledge of javascript is limited, and not up-to-date.

**Comment by pdurbin** [comment]
It turns out that $.ajax has a "headers" feature. Works great. Please see pull request #116.

**Comment by landreev** [comment]
@pdurbin I'm glad to know these were one-line fixes after all!
I'm happy to approve the PR. But could include the fix for the first part of the issue too please (whatever needs to be un-commented out there?)

**Comment by pdurbin** [comment]
@landreev ah, sorry, I talked about this in the pull request but not here. I checked with @djbrooke and I believe we determined that in this repo there is nothing to uncomment. In the pull request I included a screenshot of the expected content (except that it's from my laptop rather than prod data).

Worst case we should be able to diff the files the figure out what to uncomment.

**Comment by landreev** [comment]
@pdurbin Yes, you're right - I just came to the same conclusion independently :). 
The "recent activity" sections were only removed in the copies installed on the prod. nodes.

**Comment by djbrooke** [comment]
Thanks @pdurbin @landreev - I added it as an item here but I guess this will indeed be self-healing when we move this to prod. 🎉
