### ISSUE TITLE
Delete published version of a dataset in the Harvard Dataverse Repository (doi:10.7910/DVN/X093TV)

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#176]
Version 5 of the dataset https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/X093TV needs to be deleted. Can a developer help delete it?

Once it's confirmed that it can be deleted, the dataset's draft version can also be deleted.

For context, confusion about how versioning works in Dataverse repositories caused the depositor to create the current version 5. Deleting it will let the depositor create a new version 5. More info is in the support email at https://help.hmdc.harvard.edu/Ticket/Display.html?id=323772.

**Comment by jggautier** [comment]
It's technically possible to delete a published version, and @sbarbosadataverse and the dataset depositor gave the okay. This just needs to be prioritized by the team so that:
1. I or someone else deletes the current draft version
2. Then a developer edits the database to change the published version 5 to a draft version
3. Then I or someone else deletes that draft version, too

**Comment by landreev** [comment]
Hey, I finally read this issue (thanks for pointing me to it!). 
And I'm finally seeing that this is the second dataset from my #180!!!
So, same thing, as with [H8OFUY](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/H8OFUY) - I found this dataset when investigating the consequences of the 5.11 bug, it was one of the 2 that could not be easily recovered, so I reached out to the author directly, not knowing that there was already a support issue. So I ended up offering to them the exact thing they had already been asking for - to delete the published version 5.0, and have them try to upload the files again. They (obviously) agreed; so this has been done, as of Tue. 

Before reaching out to them, I did ask in that thread on #dv-general if there had been support requests about these two datasets. But I should've just searched RT myself. 

Anyway. I'll make a note in the RT ticket, so that it can be closed.

**Comment by jggautier** [comment]
Oh perfect!

I wonder if the "confusion about how versioning works in Dataverse repositories" was in part due to the  bug in https://github.com/IQSS/dataverse.harvard.edu/issues/180.

**Comment by landreev** [comment]
Yes, it absolutely was - that bug was the reason their published version 5.0 was showing without any files in it.

**Comment by landreev** [comment]
But yes, they opened that RT ticket on Thursday, the day before we even realized that bug was there. Reading it now, it's clear what was going on. But at that point it just sounded like they published by mistake/prematurely, and wanted the version to go away because of that.
