### ISSUE TITLE
Spike: Investigate why University of Virginia's Dataverse installation (Libra Data) can't harvest a set from Harvard Dataverse Repository

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#206]
Sherry Lake emailed Dataverse support that the University of Virginia repository she manages, Libra Data at https://dataverse.lib.virginia.edu, can't harvest a set from the Harvard Dataverse Repository. When Sherry tries, using the dataverse_json and the ddi metadata formats, no dataset records are harvested into Libra Data.

Libra Data is using Dataverse v5.11.1. Harvard's repository is using 5.12.

The set from Harvard's repository is called UVA_Authored_Datasets.

In the email thread at https://help.hmdc.harvard.edu/Ticket/Display.html?id=331127, Sherry attached a log with more technical information about the harvesting attempt.

Lastly, when I tried to harvest the set from Harvard's repository into Demo Dataverse, some records are harvested but some failed to be harvested. I'm not sure if it's helpful for this case to know why Demo Dataverse is able to harvest some records but Libra Data can't harvest any.

Definition of done:
- We know why the Libra Data repository is unable to harvest the set from the Harvard Dataverse and discuss next steps (e.g. suggesting configuration options for Libra Data, recording that this issue will be fixed when work being tracked in a related GitHub issue is done, opening another GitHub issue to describe a new bug or technical limitation)

**Comment by shlake** [comment]
I re-added Harvard as a Harvesting Client and it seemed to work (at least the whole thing did not fail). Error with the client I set up years ago just "FAILED"

> SUCCESS; 159 harvested, 0 deleted, 1 failed.

@jggautier so I think this issue can be closed.

Solution was to create a new client on the dashboard.

**Comment by jggautier** [comment]
Awesome! Glad the harvesting works now.

Is it helpful to learn why the old client wasn't working, but the new client is? Should recreating a failing set be the kind of troubleshooting method where we don't really know why it works (like turning something off and turning it on again)?

**Comment by jggautier** [comment]
In a meeting this morning (https://github.com/IQSS/dataverse/issues/8574#issuecomment-1397224187) @landreev said that yes, installation admins should consider recreating a failing set when troubleshooting harvesting issues like these.

I'll close this issue

**Comment by shlake** [comment]
@jggautier leaving a note here that my harvest (with the newly created set - on January 10th - which was a success on that day) failed today, Jan. 19th when I ran it. I had not set up a scheduled harvest. Today was the first time since then that I ran it; I manually ran it today.

So how often am I going to have to re-create a new harvest set?

Running the client created on Jan 10, immediately failed... there was no "in progress"

Running the client I just created (Jan 19) with all the same configurations as before, worked, showed "in progress" until it was completed:

<img width="1186" alt="Screen Shot 2023-01-19 at 3 13 49 PM" src="https://user-images.githubusercontent.com/3809325/213550307-9268e620-8589-445c-8ba5-59ad327e9b16.png">

**Comment by jggautier** [comment]
Sorry to hear, @shlake, and thanks for the update and the question. Ideally you'd have to recreate the set just once! Hopefully hearing that the re-created harvesting client fails when trying to harvest after the first successful run helps with troubleshooting.

Reopening this issue so it's easier to find.

**Comment by landreev** [comment]
This is alarming. I do recommend to remove and recreate a client that may have sat around for a long time, when the server on the other end may have been upgraded a few times since the last successful harvest, etc. - as a one off remedy that _may_ fix it. But no, it should not be expected to have to rebuild it from scratch every week!
Could you please send us/attach the log from that last failure. It should be in your logs directory as something like `harvest_UVA-Harvard2_2023-01-19T....`.

**Comment by landreev** [comment]
(this may or may not need a bug fix issue in the main dev. project - but yes, let's look at the log first)

**Comment by shlake** [comment]
@landreev here is a link where I put 3 harvest log files - https://virginia.box.com/s/osi8ujbgcplxxlkehhmkd2jacxh5zu3u

- one is the successful harvest from Jan10
- one is the unsuccessful harvest today (Jan 19), which was using the same harvest client set up on Jan 10th
- third file is the successful harvest from the new client set up today (Jan 19).

thanks for looking into this.

**Comment by landreev** [comment]
Thank you @shlake.
This is not looking awesome... We may have broken serving _incremental_ harvests in 5.12.1, at least for pre-5.12.1 clients. i.e., "give me everything in the set xyz" works, but "give me what's new in the set xyz since mm-dd-yyyy" is broken. And by "we" I mean I may have. 
I'll open a bugfix issue etc.

**Comment by shlake** [comment]
@landreev just an FYI.... Harvard is still at 5.12 (not 5.12.1), right?

**Comment by landreev** [comment]
Harvard is in fact running 5.12.1 in all but name. (it's running a custom, and colorfully-named emergency build that was later released as 5.12.1).

**Comment by landreev** [comment]
I produced a (very simple) fix for this. We'll just need to figure out the logistics of applying it to our prod. I will keep you posted (I need to post about this in the Google group too).

**Comment by landreev** [comment]
@shlake Could you please check and confirm that you can harvest from us again, now that we are running 5.13 (can harvest from us more than once, that is)? - Thank you!

**Comment by shlake** [comment]
@landreev Yes, it worked. The harvest found 1 new record and no errors. 👍

**Comment by landreev** [comment]
OK, thanks, that's great to hear.
