### ISSUE TITLE
Update Filetypes

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse.harvard.edu#21]
https://github.com/IQSS/dataverse/issues/2202 is merged and will be included in the next release (4.15). Once this is deployed to dataverse.harvard.edu, we should use these newfound powers to update filetypes in prod.

**Comment by djbrooke** [comment]
When we run this, we expect this to resolve https://github.com/IQSS/dataverse/issues/4156

**Comment by djbrooke** [comment]
- run the API and expect to see a reduction in the count of unknown files
- spot check on the output to see if it's what we expect

**Comment by landreev** [comment]
"Unknown" is no longer the most common type in the facet:

![Screen Shot 2019-07-22 at 11 16 50 AM](https://user-images.githubusercontent.com/737558/61644192-3eb7e880-ac72-11e9-9fbb-e0fcd97bd8b0.png)

**Comment by landreev** [comment]
> When we run this, we expect this to resolve https://github.com/IQSS/dataverse/issues/4156

Correct, they will be mime-typed "application/x-h5" that will be displayed as "Hierarchical Data Format" in the UI. 
(most of the affected files are in the next batch to go through the detector api)

**Comment by landreev** [comment]
Everybody (but especially @mheppler) is invited to watch the number in the "Unknown" facet gradually drop in real time in the next hour and a half or so.

**Comment by landreev** [comment]
No longer in the second place either... How will it end?? Stay tuned to find out!
![Screen Shot 2019-07-22 at 4 08 09 PM](https://user-images.githubusercontent.com/737558/61661886-345e1480-ac9b-11e9-9e73-bdaa66740d8a.png)

**Comment by landreev** [comment]
This is the final prod. file type facet in the default "top 5" view: 
![Screen Shot 2019-07-22 at 4 52 02 PM](https://user-images.githubusercontent.com/737558/61664704-578bc280-aca1-11e9-819b-a6b6ef037817.png)
The "unknown" category is in the 6th place, with 52K indexed files now. 

A very large portion of this change in the facet values is on account of A HUGE NUMBERS of .dcm files in a few large datasets; they were previously unrecognized, and now we type them by the extension as "application/dicom" and count as image files. The "display type" for this mime type is "DICOM Image". But all sorts of other types of files have been identified and reclassified as part of this effort too. 

Dragging this into QA - since all the code behind this had been reviewed in the process of closing the dev. issue.
