### ISSUE TITLE
robots.txt disallowing all, preventing crawling by Google etc.

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse.harvard.edu#227]
This seems like a problem...

```
$ curl https://dataverse.harvard.edu/robots.txt
User-agent: *
Disallow: /
```

... as is probably leading to datasets not being indexed by Google, as explained at https://groups.google.com/g/dataverse-community/c/hL4nt-9GQBw/m/lK4twagWAgAJ and https://iqss.slack.com/archives/C010LA04BCG/p1689270974095009

We can use https://search.google.com/test/rich-results to test. Here's [my dataset](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/TJCLKP):

![Screen Shot 2023-07-14 at 1 56 25 PM](https://github.com/IQSS/dataverse.harvard.edu/assets/21006/1467312b-6b22-4813-9644-2c5edd074fa5)

**Comment by jggautier** [comment]
Is https://github.com/IQSS/dataverse/issues/8936 related?

Since that issue was open, I've been thinking that the problem it describes is also preventing Google from index all published datasets in repositories with over 50k datasets, like Harvard's.

**Comment by pdurbin** [comment]
Yes but if you check any dataset in the sitemap with the tool above it will also show as blocked.

**Comment by pdurbin** [comment]
In https://guides.dataverse.org/en/5.13/installation/config.html#ensure-robots-txt-is-not-blocking-search-engines we recommend not letting Payara serve the robots.txt (with everything blocked) we ship in the war file.

**Comment by kcondon** [comment]
These were changed to be blocking on 6/25/23, possibly due to service instability during community meeting. I've restored the robots.txt.PRESERVED file from that time, which has a longer crawl-delay:

User-agent: *
Disallow: /
User-agent: Googlebot
User-agent: soscan (+https://dataone.org/)
Allow: /$
Allow: /dataset.xhtml
Allow: /dataverse/
Allow: /sitemap/
Allow: /api/datasets/:persistentId/thumbnail
Allow: /javax.faces.resource/images/
Disallow: /dataverse/*?q
Disallow: /dataverse/*/search
Disallow: /dataset.xhtml?*&version=&q=
Disallow: /
Crawl-delay: 100
#sitemap: https://dataverse.harvard.edu/sitemap/sitemap.xml
# Created initially using: http://www.mcanerin.com/EN/search-engine/robots-txt.asp
# Verified using: http://tool.motoricerca.info/robots-checker.phtml
