### ISSUE TITLE
Use Abacus Data Network's new server URL to harvest the installation's metadata

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#251]
Clicking on the titles of the records harvested from [Abacus Data Network](https://abacus.library.ubc.ca) into Harvard Dataverse (https://dataverse.harvard.edu/dataverse/ubc_harvested) no longer takes users to the datasets.

Abacus Data Network upgraded its Dataverse software version to v5.6 and changed its server URL to https://abacus.library.ubc.ca. The old URL, https://dvn.library.ubc.ca redirects to https://abacus.library.ubc.ca.

We'll need to harvest using new URL https://abacus.library.ubc.ca/oai.

I'm not sure if we should either:
- Edit the existing harvesting client in Harvard Dataverse so that it uses the new server URL (https://abacus.library.ubc.ca/oai), then try to harvest
- Or remove the existing client in Harvard Dataverse, then create a new one with the new server URL

**Comment by jggautier** [comment]
To see if harvesting from Abacus Data Network would work, I just told Demo Dataverse to harvest records from https://abacus.library.ubc.ca/oai into the collection at https://demo.dataverse.org/dataverse/ubc_abacus_harvested, using the dataverse_json format.

I'll check later this week to see what happens.

**Comment by cmbz** [comment]
2024/03/123
- @jggautier I added this to the GREI OAI-PMH tracking issue: https://github.com/IQSS/dataverse-pm/issues/171

**Comment by jggautier** [comment]
Just update that Demo Dataverse couldn't harvest any of the dataset metadata from Abacus using the dataverse_json metadata format.

**Comment by landreev** [comment]
Just want to put it on record that changing the server type (from "DVN" to "Dataverse") in the harvesting clients panel did NOT fix the redirects for the existing harvested records either. 
![Screen Shot 2024-03-15 at 1 00 28 PM](https://github.com/IQSS/dataverse.harvard.edu/assets/737558/e9afe43d-9ee2-45e2-96c8-d5d0f9bbf8c6)

This appears to be because they have changed all their handle identifiers - the ones we have harvested look like `hdl:11272/NNNNN`, the ones they are using now - `hdl:11272.1/AB2/XXXXX`. 
The actual old handles are still redirecting properly, if you click on them: 
![Screen Shot 2024-03-15 at 1 08 32 PM](https://github.com/IQSS/dataverse.harvard.edu/assets/737558/5d3a9393-6a33-44b6-9cc1-ac7e9a69bce4)
so they are still registered on the handlenet side. But the Abacus' new Dataverse no longer recognizes them, when we try to redirect there directly. 

... one way or another, these records are hopelessly stale. We do need to delete this client and re-harvest. I agree it's prudent to first work out a working configuration on demo. If dataverse_json isn't working, we should follow the normal downgrade route - to oai_ddi, and then to oai_dc, if that's not working either.

**Comment by landreev** [comment]
Hah, I was able to fix the redirects for the old harvested records in prod, by changing to "generic" and using the handle resolver as the archive url: 
![Screen Shot 2024-03-15 at 1 23 46 PM](https://github.com/IQSS/dataverse.harvard.edu/assets/737558/73b2c97e-df3c-4b58-b5d6-f4ba91b851bd)

Haven't tried all of them, but the ones I tried worked. 
This does NOT change the fact that we want to be able to re-harvest from their new server and to restart regular harvesting from them.

**Comment by landreev** [comment]
On demo every record failed with the same exception: 
`Failed to import harvested dataset: class edu.harvard.iq.dataverse.util.json.JsonParseException (Invalid license: ...)`

I'll need to refresh my memory on what this means.

**Comment by landreev** [comment]
Please go ahead and try the other formats, no need to wait. 
(you will need to either delete and recreate the client; or purge the clientharvestrun entry from the database; otherwise it'll attempt to harvest incrementally, since the date/time of the last so called "success". sorry if I'm explaining the obvious)

You are most likely correct, about the json format. That was my guess, that it's completely incompatible between pre- and post-5.10, because of the license change. Just wanted to confirm this w/ others in dv-tech.

**Comment by jggautier** [comment]
Using oai_ddi worked mostly.

It looks like 2,435 records were harvested into https://demo.dataverse.org/dataverse/ubc_abacus_harvested. The [harvesting client page](https://demo.dataverse.org/harvestclients.xhtml?dataverseId=1) says that 3 failed.

And it looks like there are 2,449 datasets in the repository (https://abacus.library.ubc.ca), although maybe a few of those are missing in their oai feed because they were published very recently.

Want me to delete the client in Harvard Dataverse and re-create a new one using oai_ddi instead?

**Comment by landreev** [comment]
Yes, that's a very good success-to-fail ratio, let's use oai_ddi in prod. 
I would only suggest to wait to run the actual harvest until the weekend.

**Comment by jggautier** [comment]
Just leaving an update that the old client was deleted and I created a new client using the https://abacus.library.ubc.ca/oai. It's scheduled to run Saturdays at 4am.

I'll check on Monday to see how it went 🤞

**Comment by jggautier** [comment]
The harvesting client page for HDV says that the scheduled harvest ran on Saturday at 4 amd and 2,438 records were harvested into https://dataverse.harvard.edu/dataverse/ubc_harvested. It failed to harvest 3 records.

I'm going to close this issue.

**Comment by landreev** [comment]
I saw that last night. Going to consider this a smashing success, by our standards.
