### ISSUE TITLE
Add 3D data viewer to HDV

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse.harvard.edu#256]
3D viewer in a Dataverse Installation (select a 3D file to view the 3D viewer) https://dataverse.openforestdata.pl/dataset.xhtml?persistentId=doi:10.48370/OFD/Y8TNUO

related to: https://github.com/IQSS/dataverse.harvard.edu/issues/253

**Comment by cmbz** [comment]
2024/03/27
Prioritized at @siacus request ([Slack thread](https://iqss.slack.com/archives/GRDNRJ6BZ/p1710775634212279))

**Comment by landreev** [comment]
Could please add the info on the actual viewer tool that needs to be installed - the source of it/the Dataverse manifest for it, etc. I'm not immediately seeing it in the slack thread linked and/or the doc. linked from issue #253.

**Comment by landreev** [comment]
(otherwise this would take a minute to add in prod.)

**Comment by sbarbosadataverse** [comment]
> Could somebody please add the info on the actual viewer tool that needs to be installed - the source of it/the Dataverse manifest for it, etc. I'm not immediately seeing it in the slack thread linked and/or the doc. linked from issue #253.

@Leonid, I don't have the name of the tool that is why I included the DV that is using it so we can connect with them for the information.

**Comment by landreev** [comment]
Has somebody been in touch with them already, Matt Cook maybe?

**Comment by qqmyers** [comment]
FWIW: From this paper (https://www.researchgate.net/publication/354871831_Open_Forest_Data_Digitalizing_and_building_an_online_repository), it appears that they are just wrapping https://github.com/kovacsv/Online3DViewer which has an MIT license. The browser console on shows on minimized js getting downloaded so they must have integrated everything. I didn't immediately see a repo for the Dataverse-specific work.

**Comment by pdurbin** [comment]
@kamil386 presented the Open Forest Data tool at the 2020 Dataverse community meeting. I just emailed him to see if it's open source. Here are the slides, by the way:  [External tools for advanced data visualization in hard sciences.pdf](https://github.com/IQSS/dataverse.harvard.edu/files/14921217/External.tools.for.advanced.data.visualization.in.hard.sciences.pdf)

**Comment by landreev** [comment]
Is this issue asking for a "waiting" tag? @donsizemore and @pdurbin both contacted the instance in question via different routes for the source info. The installation here at HDV is pending/waiting for that information.

**Comment by pdurbin** [comment]
I also went ahead and asked the community, why not: https://groups.google.com/g/dataverse-community/c/D-vGQ5JP_7I/m/9uQcHTjVAAAJ

**Comment by Cook4986** [comment]
Additional, open-source/open-access 3D web viewers with academic/scholarly user bases:

- [Voyager ](https://smithsonian.github.io/dpo-voyager/)
  - Smithsonian-based
 - [Universal Viewer](https://universalviewer.io/)
   - Supports IIIF 
- [Babylon.js](https://www.babylonjs.com/)
- [x3Dom](https://www.x3dom.org/)

**Comment by landreev** [comment]
I saw https://github.com/gdcc/dataverse-previewers/pull/56. If anyone feels positive that it's ready for prod. use, just let me know. Otherwise we'll wait until it's merged.

**Comment by landreev** [comment]
@Cook4986 Which specific 3D file format(s) is your group going to be using? - is there a list of formats that we want Dataverse users to be able to preview?

**Comment by sbarbosadataverse** [comment]
Noting that the prefered tool for Matt Cook's team at Harvard Library is "Voyager"  https://smithsonian.github.io/dpo-voyager/

**Comment by landreev** [comment]
With luck, the basic framework of the 2 known Dataverse 3D viewers (based around Online3DViewer and X_ITE) could be replicated to build a Voyager-based tool as well. ... But it'll still be a bit of a dev. and testing effort.

**Comment by sbarbosadataverse** [comment]
Created a previewer issue in GDCC to support Voyager for Harvard Library: 

- https://github.com/gdcc/dataverse-previewers/issues/57

**Comment by landreev** [comment]
> Additional, open-source/open-access 3D web viewers with academic/scholarly user bases:
> 
>     * [Voyager ](https://smithsonian.github.io/dpo-voyager/)
>       
>       * Smithsonian-based
> 
>     * [Universal Viewer](https://universalviewer.io/)
>       
>       * Supports IIIF
> 
>     * [Babylon.js](https://www.babylonjs.com/)
> 
>     * [x3Dom](https://www.x3dom.org/)

@Cook4986 To clarify, in the context of integration with Dataverse, we can't just use arbitrary viewers, like the ones you listed, "off the shelf". In order to work with Dataverse, a web app needs to conform to our specifications of what we call a "Dataverse external tool" - basically, it needs to understand the bare minimum of our API to be able to talk to Dataverse and retrieve files from it.

With open source tools like the ones above, it is usually a matter of adding an extra javascript wrapper around their libraries that provides this functionality. It's relatively lightweight, there are standard templates that can be reused, and there is a community-driven development project (outside of the core Dataverse development) - https://github.com/gdcc/dataverse-previewers for creating such tools. As an example, here's a new/experimental 3D viewer tool that has been created based on the X_ITE library: https://github.com/gdcc/dataverse-previewers/pull/56. 

"Integration" with Datavese is of course the key word. We are talking about a tool that can be plugged into the framework of the application, allowing our users to launch it on a Dataverse-served file with a single click in the application UI, in a new tab or embedded, etc. A user can of course download files from Dataverse, and use any tool of their liking on it outside of the application. 

In most cases, creating a new Dataverse viewer tool around an existing library is not much of a development effort. But it is still something that somebody needs to work on and build. It is possible that a viewer based on Voyager can be created relatively easily, but it is not going to happen instantly. In the context of this issue we are adding an already existing tool created by another Dataverse group (linked in the opening comment) to our prod. server. We should be able to have it installed shortly. Going forward, we hopefully will be adding more viewer tools as they become available.

**Comment by cmbz** [comment]
2024/05/08
- Next steps, add to demo and ask @Cook4986 to test

**Comment by PaulBoon** [comment]
@Cook4986 If you start testing that X_ITE base previewer please have a look at the initial attempt to use that 'Online3DViewer' for which I have made this draft PR: https://github.com/gdcc/dataverse-previewers/pull/58. 
While fiddling with some data files, I was getting the impression that the 'Online3DViewer' was a bit better in rendering different files and formats than the X_ITE based previewer. However, it lacked a menu and it had similar problems with the initial view not showing the mode. These problems might be solvable with a bit of coding, but that would take some time to figure out. 

It would be interesting to know how the 'Open Forest Data' has made that tool work, most likely it is simpler to integrate as an 'explore' tool because it is meant to be a 'site' and not to be frames on another page.

**Comment by pdurbin** [comment]
> It would be interesting to know how the 'Open Forest Data' has made that tool work

I forget if we've shared this link already (too many issues and pull requests!) but please see https://github.com/OpenForestData/open-forest-data-previewers

**Comment by landreev** [comment]
Here's a trial install of the Openforestdata.pl 3dViewer tool in prod.: 
![Screen Shot 2024-05-13 at 8 32 58 PM](https://github.com/IQSS/dataverse.harvard.edu/assets/737558/7b804a75-ec39-4171-a8fe-11d19205918e)
The file in the screenshot: https://dataverse.harvard.edu/file.xhtml?fileId=7559161&version=1.1
Should be working on any STL file as of now; more mime types will be supported going forward. May still need to iron out some kinks... 

Huge thanks to Kamil Guryn from Openforestdata, and to @pdurbin for the help!

**Comment by landreev** [comment]
The viewer also works for `image/x-3ds` and `application/x-tgif` types.

**Comment by landreev** [comment]
I'm going to close this issue, since it was opened and estimated as a quick prod. server config  change only. 
I suggest we continue the discussion of adding more tools going forward, based on other underlying libraries/supporting more file types etc., somewhere in the https://github.com/gdcc/dataverse-previewers github project. For example, in https://github.com/gdcc/dataverse-previewers/pull/56 (new X_ITE-based tool under development) or https://github.com/gdcc/dataverse-previewers/issues/57 (a new issue inquiring about a tool based on Voyager).

**Comment by pdurbin** [comment]
As discussed in standup, I created a PR to add this tool to the guides:

- https://github.com/IQSS/dataverse/pull/10562

Thanks again, @kamil386!

**Comment by pdurbin** [comment]
@Cook4986 I could be mistaken but I think the previewer was only added for content type "application/vnd.ms-pki.stl". Would you be able to open a fresh issue for additional content types? Some of our previewers work for multiple content types (JPG, GIF, PNG, for example), but we have to add them multiple times, once for each type.

Good question about preview vs. explore. You would prefer preview? And yes, that demo looks great.

**Comment by landreev** [comment]
@Cook4986 @pdurbin The installed viewer will also work on `image/x-3ds` and `application/x-tgif`, it is mentioned somewhere above. This is the configuration that the authors passed to us (our viewers are tied to/configured for mime types), that I copied as is. But I will ask them if it is supposed to work on anything else, including X3D. There's a chance that it is, and they only configured it for the 3 types above because that's what their archive uses. 

There's also a good chance that this viewer does NOT work on any, or some of the formats that you need. But we are going to continue soliciting/looking for more viewers to add. Phil suggested opening a new issue requesting support for more types, but it may make sense to first ask in https://github.com/gdcc/dataverse-previewers/pull/56 (?)

**Comment by landreev** [comment]
@Cook4986 @pdurbin
It doesn't seem to be working with x3d - I just tried it with a `model/x3d+xml` file, and got "unsupported file type".

**Comment by landreev** [comment]
@Cook4986 I installed the experimental X_ITE-based viewer discussed above, as part of the overall viewers upgrade in #242. 
I can see  that it at least opens on X3D files. For example, one of your files:
https://dataverse.harvard.edu/file.xhtml?fileId=7127236&version=1.0&toolType=PREVIEW
I haven't tested it much otherwise. 

It is of course still in beta, and advertised as such on the dataset page.

**Comment by Cook4986** [comment]
It's great to preview one of our models on DV, @pdurbin and @landreev ! Can we test a tweak X_ITE that disables [the default environmental lighting](https://create3000.github.io/x_ite/tutorials/lighting-your-world/)? Our scans are [set to "shadeless" on Sketchfab](https://sketchfab.com/blogs/community/how-to-fine-tune-your-lighting-and-shadows-on-sketchfab/#rendermode), which better reveals surface details - like the "2060" label of [this Granite scan for example](https://sketchfab.com/3d-models/porphyritic-granite-76a4924782ee4eb3b3bca3e67216f84c).

**Comment by pdurbin** [comment]
@Cook4986 would you be able to open an issue at https://github.com/gdcc/dataverse-previewers ? Perhaps we can get @PaulBoon's attention since he added the initial implementation:

- https://github.com/gdcc/dataverse-previewers/pull/56

**Comment by Cook4986** [comment]
See new [previewers repo issue #68](https://github.com/gdcc/dataverse-previewers/issues/68) for further testing/debugging discussion
