### ISSUE TITLE
Upgrade HDV production to 6.4

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse.harvard.edu#307]
## Overview
- Now that 6.4 has been released and demo.dataverse.org upgraded, dataverse.harvard.edu need to be upgraded from 6.3 to 6.4, too.

## Tasks
- [x] Upgrade Harvard Dataverse repository to 6.4

**Comment by cmbz** [comment]
Closing as already completed. Oops!

**Comment by landreev** [comment]
This has been done. Can be closed, once confirmed that there's nothing seriously broken.

**Comment by landreev** [comment]
OK, yes, let's keep it open for a couple more days on account of a couple of outstanding tasks - primarily, the Datacite metadata update. I wanted to put a little bit of extra thought into the process and verify whether it is safe to just run it as one bulk job as described in the upgrade instruction; or if it is worth running it in some way that is slower and easier on the servers. 
(this is something that needs to be done, in order to take advantage of something added in 6.4, that will allow us to improve what Datacite knows and advertises about our holdings; but not a requirement in terms of the site itself working properly)

**Comment by landreev** [comment]
As a matter of fact, with the DataCite metadata update, there are still a few thousand datasets to go. But I feel it is safe to close the issue as completed.
