### ISSUE TITLE
Update watermarks of the (QDR) 'External Vocabulary' scripts that have been applied on the Author and Funding fields on demo.dataverse.org

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse.harvard.edu#327]
## Overview
- After UX review and discussion, we will deploy 'External Vocabulary' scripts, developed by QDR, to the Author and Funding fields on Harvard Dataverse. See: https://github.com/IQSS/dataverse.harvard.edu/issues/326
- So that we can collect feedback about changed to the fields (e.g. usability  testing and passive requests for feedback), we'll need to change the watermark  text of the Author Name, Author Affiliation, and Funding Information Agency fields with [language suggested by @jggautier](https://github.com/IQSS/dataverse.harvard.edu/issues/326#issuecomment-2528895775). This way the changes match the changes we'll make on Harvard Dataverse:

  <kbd><img width="948" alt="Screenshot 2024-12-10 at 5 16 35 PM" src="https://github.com/user-attachments/assets/2df3cc66-ff96-4979-9058-579ae7baa655"></kbd>

  <kbd><img width="952" alt="Screenshot 2024-12-10 at 5 16 40 PM" src="https://github.com/user-attachments/assets/9057bcb7-9e93-4975-bf23-06371867a969"></kbd>

## Related
- https://github.com/IQSS/dataverse.harvard.edu/issues/326

**Comment by cmbz** [comment]
2024/12/10: Preliminary sizing of 3, please resize as needed to reflect actual work.

**Comment by qqmyers** [comment]
Demo is updated with the latest ORCID/ROR scripts, including new 'Select or enter...; placeholders, and styling from #11106.

FWIW: The ability customize the placeholder dynamically is supported by the scripts, but evidently not in Dataverse itself. The data-cvoc-placeholder param isn't in the external vocab schema and the Dataverse code always sends the value "" for it. For now, I expect 'Select or enter...' is fine for everyone but if we want the ability for sites to customize, it is still to be built.

**Comment by cmbz** [comment]
@jggautier is this [a functionality](https://github.com/IQSS/dataverse.harvard.edu/issues/327#issuecomment-2549675831) you think that users will want? If so, can you create an issue with the right GREI labels, add to the GREI 2 tracking issue, and then make sure we discuss at the next prioritization meeting? Thanks!

**Comment by jggautier** [comment]
Hi @cmbz and @qqmyers. I'd like to understand this better.

When installation admins change their repository's fields to use the controlled vocabulary functionality, wouldn't they be able to customize the placeholder in the same way that you changed it for Demo Dataverse @qqmyers?

**Comment by qqmyers** [comment]
I changed it here- https://github.com/gdcc/dataverse-external-vocab-support/blob/dce1a0d3788ab316b03e893b8085faafb1854937/scripts/people.js#L133 because the data-cvoc-placeholder setting is not yet being sent. So yes - anyone could edit the script, but they'd be forking the script rather than changing a config setting for their local Dataverse.

**Comment by jggautier** [comment]
Ah that helps. Thanks @qqmyers.

I'm not sure if other installation admins will want to more easily change the placeholders. But admins from QDR and DANS are already using this, right? And a couple of other installations have checked out the changes on Demo Dataverse before the placeholder was changed and it seemed like they were interested in using the external controlled vocabulary functionality to change one or more fields in their Dataverse installations. I could follow up to ask them, but @qqmyers would you happen to know what placeholders QDR and DANS are using now? If they don't plan to use "Select or enter...", I imagine they'll want to make sure they can use other placeholder text without having to fork the script, too.

**Comment by qqmyers** [comment]
My guess is that no one will care about the current change but being able to change and/or internationalize it in the future is useful, although not really a priority at the moment.

**Comment by jggautier** [comment]
Ah okay. I'll take that to mean that QDR and DANS are not using "Select or enter...", but you think other installations would want to, or at least want to be able to change the language of the placeholders, which means that the ability to customize the placeholder dynamically would need to be supported in Dataverse itself.

I think I understand enough to create a GitHub issue and add the GREI 2 tracking issue. I'll leave a note to remind myself to bring it up at the next prioritization meeting.

Since the watermarks/placeholder text has been changed for the fields on Demo Dataverse, I'll close this GitHub issue.
