### ISSUE TITLE
Add accessibility link to the footer for dataverse.harvard.edu

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse.harvard.edu#46]
Add an “Accessibility” link to customization footer of the Harvard Dataverse.

Accessibility link URL: https://accessibility.huit.harvard.edu/digital-accessibility-policy

**Comment by mheppler** [comment]
@kcondon, I have added a new `resourcesProd-2019-12-12.zip` file to the Google Drive directory, "Dataverse > Harvard Dataverse > Harvard Dataverse Customization".

The only changes were made to the `harvard-dataverse-footer.html` file, and I utilized some jQuery to append an "Accessibility" link to the app's footer.

```
<script>
  //<![CDATA[
  $(document).ready(function () {
    $("#footer > div.container > div.row > div.col-sm-8.small > p").append("&#160;|&#160; <a href=\"https://accessibility.huit.harvard.edu/digital-accessibility-policy\" target=\"_blank\" rel=\"noopener\">Accessibility</a>");
  });
  //]]>
</script>
```

Since our customization does not add a legitimate footer to the bottom of the page, I decided it was most appropriate just to tack this link on to the end of the existing app footer, after the copyright and privacy policy link.

Here is a mocked up screenshot of how it should look on production.

![Screen Shot 2019-12-12 at 2 08 17 PM](https://user-images.githubusercontent.com/687227/70741266-e482f700-1ce8-11ea-997e-c1d3c279081f.png)

Going to move this code review for the team to review. No PR for this one. This comment should be enough to review.

**Comment by pdurbin** [comment]
This all sounds fine and I'm moving it to QA. I didn't open the zip but the comment above makes sense (thanks for the screenshot).

I guess my only actual feedback is that since we have this dedicated git repo called "dataverse.harvard.edu" maybe in the future we could use it for stuff like customizations for Harvard Dataverse. The only problem with this is that we also use the issue tracker for demo (#19), beta (#20) and dev/qa servers (#44). So this git repo doesn't feel like it's dedicated to Harvard Dataverse. The issue tracker at least is more of a catchall for stuff that's a bit off topic for the core "dataverse" git repo.

**Comment by kcondon** [comment]
Done
