### ISSUE TITLE
On Demo Dataverse, add fake file-level PIDs

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#49]
@sbarbosadataverse (and others) often use Demo Dataverse to demonstrate how Harvard Dataverse works, and asked that files get fake DOIs to mirror the functionality of Harvard Dataverse

**Comment by pdurbin** [comment]
"@sekmiller pointed out that the fake PID providers doesn't support file DOIs" -- https://github.com/IQSS/dataverse/pull/5399#issuecomment-448289416

Because this, a change to the code is required. So an issue at https://github.com/IQSS/dataverse/issues should be created (and this issue could be about turning on file PIDs when the code has been deployed to demo).

Of course, I'm making an assumption that demo is using the "FAKE" DOI provider. We should check.

**Comment by jggautier** [comment]
Files on Demo Dataverse have fake DOIs now, e.g.:
- https://demo.dataverse.org/file.xhtml?persistentId=doi:10.70122/FK2/POABN5/WUDNON
- https://demo.dataverse.org/file.xhtml?persistentId=doi:10.70122/FK2/MZRJ2G/BVQS4Q

Not sure when this happened. Is it the result of work described in https://github.com/IQSS/dataverse/issues/6646? Will the files on Demo Dataverse continue to get fake DOIs?

**Comment by qqmyers** [comment]
I think these are DataCite test DOIs, not ones from the FAKE provider (which just returns "fakeIdentifier" for the value).

**Comment by jggautier** [comment]
Ah, thanks @qqmyers.

Is it planned that Demo Dataverse will continue giving these test DOIs to files, or will Demo eventually use DOIs from the FAKE provider? Is it preferred that Demo Dataverse and other installations created for testing purposes use DOIs from the FAKE provider instead of DataCite test DOIs?

**Comment by jggautier** [comment]
I'm going to close this issue. Files on Demo Dataverse have been getting test DOIs.

My questions from last August seem moot to be honest, since I don't think people using Demo Dataverse to test Dataverse software functionality will care if it's using DataCite test DOIs or DOIs from the FAKE provider.
